In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('data/song_lyrics_en.csv')
df.head()

,Unnamed: 0,title,tag,artist,year,views,features,lyrics,id,language_cld3,language_ft,language
0,0,Killa Cam,rap,Cam'ron,2004,173166,"{""Cam\\'ron"",""Opera Steve""}","[Chorus: Opera Steve & Cam'ron]\nKilla Cam, Ki...",1,en,en,en
1,1,Can I Live,rap,JAY-Z,1996,468624,{},"[Produced by Irv Gotti]\n\n[Intro]\nYeah, hah,...",3,en,en,en
2,2,Forgive Me Father,rap,Fabolous,2003,4743,{},Maybe cause I'm eatin\nAnd these bastards fien...,4,en,en,en
3,3,Down and Out,rap,Cam'ron,2004,144404,"{""Cam\\'ron"",""Kanye West"",""Syleena Johnson""}",[Produced by Kanye West and Brian Miller]\n\n[...,5,en,en,en
4,4,Fly In,rap,Lil Wayne,2005,78271,{},"[Intro]\nSo they ask me\n""Young boy\nWhat you ...",6,en,en,en


In [5]:
df['tag'].unique().size

6

In [6]:
df['artist'].size

3374198

In [7]:
df['artist'].unique().size

429060

In [14]:
pip install tensorflow

INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.3/189.3 MB 31.3 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 26.0 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 29.5 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 25.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 24.4 MB/s eta 0:00:0000:01
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: numpy
    Found existing installation: 

In [15]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [17]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

categorical_data = df['tag']

# Step 1: Label Encoding
label_encoder = LabelEncoder()
categorical_encoded = label_encoder.fit_transform(categorical_data)

# Step 2: Embedding Layer (e.g., embedding dimension is 4)
inputs = tf.keras.Input(shape=(1,))
embedding = tf.keras.layers.Embedding(input_dim=len(label_encoder.classes_), output_dim=2)(inputs)

# 建立模型
model = tf.keras.Model(inputs=inputs, outputs=embedding)
embeddings = model.predict(categorical_encoded)

print(embeddings)


105444/105444 [==============================] - 16s 154us/step
[[[ 0.0165544  -0.00402781]]

 [[ 0.0165544  -0.00402781]]

 [[ 0.0165544  -0.00402781]]

 ...

 [[ 0.0330654  -0.01495882]]

 [[ 0.0330654  -0.01495882]]

 [[ 0.01699873 -0.00627523]]]


In [18]:
np.save('data/tag_embeddings.npy', embeddings)

In [19]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

categorical_data = df['artist']

# Step 1: Label Encoding
label_encoder = LabelEncoder()
categorical_encoded = label_encoder.fit_transform(categorical_data)

# Step 2: Embedding Layer (e.g., embedding dimension is 2)
inputs = tf.keras.Input(shape=(1,))
embedding = tf.keras.layers.Embedding(input_dim=len(label_encoder.classes_), output_dim=600)(inputs)

# 建立模型
model = tf.keras.Model(inputs=inputs, outputs=embedding)
embeddings = model.predict(categorical_encoded)

print(embeddings)


105444/105444 [==============================] - 18s 174us/step
[[[ 0.02713687 -0.00298351 -0.01549757 ...  0.01726342 -0.01173031
    0.01124358]]

 [[-0.03407858  0.00125379 -0.02351308 ...  0.0499396   0.03548752
   -0.03841626]]

 [[ 0.03889323 -0.04911338  0.03358281 ... -0.00950779  0.00706074
    0.0048405 ]]

 ...

 [[-0.03601215 -0.02035236  0.04388214 ... -0.02065318  0.04229336
    0.0294624 ]]

 [[ 0.03888479 -0.01639177  0.04376985 ...  0.03723652 -0.00815464
   -0.02036351]]

 [[ 0.04938439  0.00286299 -0.00457742 ... -0.02190952  0.04309181
    0.01712788]]]


In [26]:
np.save('data/artist_embeddings.npy', embeddings)